"""edit blog

Revision ID: 11dab42d4f24
Revises: 033bc11fc6ed
Create Date: 2025-01-08 23:06:53.785968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11dab42d4f24'
down_revision: Union[str, None] = '033bc11fc6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('address_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'address_name')
    # ### end Alembic commands ###
