"""edit user and blog table

Revision ID: 3bb4258fee55
Revises: 78775bb6ca83
Create Date: 2025-01-09 12:23:31.281521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb4258fee55'
down_revision: Union[str, None] = '78775bb6ca83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('main_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'main_image_url')
    # ### end Alembic commands ###
