"""resolve errors

Revision ID: 6d917caae9a0
Revises: f5c34d0d30ce
Create Date: 2025-01-18 04:00:36.886733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d917caae9a0'
down_revision: Union[str, None] = 'f5c34d0d30ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'default_category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'default_category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
