"""Initial migration

Revision ID: 9741662cd9a8
Revises: 933831dda7d6
Create Date: 2025-01-21 07:47:50.000107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9741662cd9a8'
down_revision: Union[str, None] = '933831dda7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Article', 'hometopic_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Article', 'hometopic_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
