"""merge branches

Revision ID: 9e79bb7f7327
Revises: ed41db80fbd6
Create Date: 2025-01-21 00:15:32.761563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e79bb7f7327'
down_revision: Union[str, None] = 'ed41db80fbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('views', sa.Integer(), nullable=False))
    op.alter_column('blog_subscription', 'subscriber_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('blog_subscription', 'subscribed_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_constraint('blog_subscription_ibfk_1', 'blog_subscription', type_='foreignkey')
    op.drop_constraint('blog_subscription_ibfk_2', 'blog_subscription', type_='foreignkey')
    op.create_foreign_key(None, 'blog_subscription', 'blog', ['subscribed_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'blog_subscription', 'blog', ['subscriber_id'], ['id'], ondelete='SET NULL')
    op.add_column('notification', sa.Column('blog_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'notification', 'blog', ['blog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'blog_id')
    op.drop_constraint(None, 'blog_subscription', type_='foreignkey')
    op.drop_constraint(None, 'blog_subscription', type_='foreignkey')
    op.create_foreign_key('blog_subscription_ibfk_2', 'blog_subscription', 'blog', ['subscriber_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('blog_subscription_ibfk_1', 'blog_subscription', 'blog', ['subscribed_id'], ['id'], ondelete='CASCADE')
    op.alter_column('blog_subscription', 'subscribed_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('blog_subscription', 'subscriber_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('Article', 'views')
    # ### end Alembic commands ###
