"""add pagination

Revision ID: a7e8d42020da
Revises: ae27d20c275f
Create Date: 2025-01-18 03:19:46.741624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e8d42020da'
down_revision: Union[str, None] = 'ae27d20c275f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('description', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Article', 'description')
    # ### end Alembic commands ###
