"""Fix missing migrations

Revision ID: ae27d20c275f
Revises: b5f81a5e0fca
Create Date: 2025-01-16 14:47:58.794930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae27d20c275f'
down_revision: Union[str, None] = 'b5f81a5e0fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('description', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Article', 'description')
    # ### end Alembic commands ###
