"""add pagination

Revision ID: c0192e7e33fa
Revises: 66e134f95f2a
Create Date: 2025-01-23 00:30:04.080478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0192e7e33fa'
down_revision: Union[str, None] = '66e134f95f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hometopic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hometopic_name'), 'hometopic', ['name'], unique=False)
    op.add_column('Article', sa.Column('hometopic_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'Article', 'hometopic', ['hometopic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('blog_subscription_ibfk_2', 'blog_subscription', type_='foreignkey')
    op.drop_constraint('blog_subscription_ibfk_1', 'blog_subscription', type_='foreignkey')
    op.create_foreign_key(None, 'blog_subscription', 'blog', ['subscribed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'blog_subscription', 'blog', ['subscriber_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_comment_article_id'), 'comment', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_article_id'), table_name='comment')
    op.drop_constraint(None, 'blog_subscription', type_='foreignkey')
    op.drop_constraint(None, 'blog_subscription', type_='foreignkey')
    op.create_foreign_key('blog_subscription_ibfk_1', 'blog_subscription', 'blog', ['subscribed_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('blog_subscription_ibfk_2', 'blog_subscription', 'blog', ['subscriber_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'Article', type_='foreignkey')
    op.drop_column('Article', 'hometopic_id')
    op.drop_index(op.f('ix_hometopic_name'), table_name='hometopic')
    op.drop_table('hometopic')
    # ### end Alembic commands ###
